services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-neko
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_data-neko:/data/db

volumes:
  mongodb_data-neko:
    driver: local